### ISSUE TITLE
testing on windows has issues

### ISSUE THREAD

**Issue by umasaxena** [acidgenomics/basejump#158]
> BiocManager::install("acidgenomics/basejump")
Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.2 (2018-12-20)
Installing github package(s) 'acidgenomics/basejump'
Downloading GitHub repo acidgenomics/basejump@master
acidgenomics-basejump-650045d/NEWS.md: Can't create '\\\\?\\C:\\Users\\UMA~1.SAX\\AppData\\Local\\Temp\\RtmpQL4ybQ\\remotes25a105a8266a1\\acidgenomics-basejump-650045d\\NEWS.md'
tar.exe: Error exit delayed from previous errors.
These packages have more recent versions available.
Which would you like to update?

 1:   BiocParallel (1.16.5 -> 1.16.6 ) [CRAN]   2:   dplyr        (0.7.8  -> 0.8.0.1) [CRAN]   3:   GenomeInfoDb (1.18.1 -> 1.18.2 ) [CRAN]
 4:   purrr        (0.2.5  -> 0.3.2  ) [CRAN]   5:   Rcpp         (1.0.0  -> 1.0.1  ) [CRAN]   6:   stringr      (1.3.1  -> 1.4.0  ) [CRAN]
 7:   tibble       (2.0.1  -> 2.1.1  ) [CRAN]   8:   tidyr        (0.8.2  -> 0.8.3  ) [CRAN]   9:   CRAN packages only                     
10:   All                                      11:   None                                     
Enter one or more numbers separated by spaces, or an empty line to cancel

**Comment by mjsteinbaugh** [comment]
Thanks @umasaxena. I followed up with an additional report in the remotes package repo. https://github.com/r-lib/remotes/issues/334

**Comment by mjsteinbaugh** [comment]
@umasaxena Yeah this is a known issue with installing R packages from GitHub on Windows. The package should install on Windows even with these warnings. Let me know if you run into any issues.

This command can be helpful for debugging:

```r
remotes::update_packages(packages = TRUE, upgrade = "always", quiet = FALSE)
```
